AR = '/usr/bin/ar'
ARFLAGS = 'rcs'
BINDIR = '/media/Data/Year3_sem1/AILP/ailp_env/bin'
CC = ['/usr/bin/gcc']
CCFLAGS = ['-std=c99', '-Wall']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'gcc'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('5', '4', '0')
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_PYEMBED = ['-pthread', '-fwrapv', '-fstack-protector-strong', '-fstack-protector-strong', '-flto', '-fuse-linker-plugin', '-ffat-lto-objects', '-fno-strict-aliasing']
CFLAGS_PYEXT = ['-pthread', '-fwrapv', '-fstack-protector-strong', '-fstack-protector-strong', '-flto', '-fuse-linker-plugin', '-ffat-lto-objects', '-fno-strict-aliasing']
CFLAGS_cshlib = ['-fPIC']
COMPILER_CC = 'gcc'
CPPPATH_ST = '-I%s'
CXXFLAGS_PYEMBED = ['-pthread', '-fwrapv', '-fstack-protector-strong', '-fstack-protector-strong', '-flto', '-fuse-linker-plugin', '-ffat-lto-objects']
CXXFLAGS_PYEXT = ['-pthread', '-fwrapv', '-fstack-protector-strong', '-fstack-protector-strong', '-flto', '-fuse-linker-plugin', '-ffat-lto-objects']
DATADIR = '/media/Data/Year3_sem1/AILP/ailp_env/share'
DATAROOTDIR = '/media/Data/Year3_sem1/AILP/ailp_env/share'
DEFINES = []
DEFINES_PYEMBED = ['NDEBUG']
DEFINES_PYEXT = ['NDEBUG']
DEFINES_ST = '-D%s'
DEST_BINFMT = 'elf'
DEST_CPU = 'x86_64'
DEST_OS = 'linux'
DOCDIR = '/media/Data/Year3_sem1/AILP/ailp_env/share/doc/pycairo'
DVIDIR = '/media/Data/Year3_sem1/AILP/ailp_env/share/doc/pycairo'
EXEC_PREFIX = '/media/Data/Year3_sem1/AILP/ailp_env'
HAVE_CAIRO = 0
HAVE_PYTHON_H = 0
HTMLDIR = '/media/Data/Year3_sem1/AILP/ailp_env/share/doc/pycairo'
INCLUDEDIR = '/media/Data/Year3_sem1/AILP/ailp_env/include'
INCLUDES_CAIRO = ['/usr/local/include/cairo', '/usr/local/include/pixman-1', '/usr/include/glib-2.0', '/usr/lib/x86_64-linux-gnu/glib-2.0/include', '/usr/include/freetype2', '/usr/include/libpng12']
INCLUDES_PYEMBED = ['/usr/include/python3.4m']
INCLUDES_PYEXT = ['/usr/include/python3.4m']
INFODIR = '/media/Data/Year3_sem1/AILP/ailp_env/share/info'
LIBDIR = '/media/Data/Year3_sem1/AILP/ailp_env/lib'
LIBEXECDIR = '/media/Data/Year3_sem1/AILP/ailp_env/libexec'
LIBPATH_CAIRO = ['/usr/local/lib']
LIBPATH_PYEMBED = ['/usr/lib/python3.4/config-3.4m-x86_64-linux-gnu']
LIBPATH_PYEXT = ['/usr/lib/python3.4/config-3.4m-x86_64-linux-gnu']
LIBPATH_PYTHON3.4 = ['/usr/lib/python3.4/config-3.4m-x86_64-linux-gnu']
LIBPATH_ST = '-L%s'
LIB_CAIRO = ['cairo']
LIB_PYEMBED = ['python3.4']
LIB_PYEXT = ['python3.4']
LIB_PYTHON3.4 = ['python3.4']
LIB_ST = '-l%s'
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_PYEMBED = ['-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-pthread', '-Wl,-O1', '-Wl,-Bsymbolic-functions', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro']
LINKFLAGS_PYEXT = ['-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-pthread', '-Wl,-O1', '-Wl,-Bsymbolic-functions', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro', '-Wl,-Bsymbolic-functions', '-Wl,-z,relro']
LINKFLAGS_cshlib = ['-shared']
LINKFLAGS_cstlib = ['-Wl,-Bstatic']
LINK_CC = ['/usr/bin/gcc']
LOCALEDIR = '/media/Data/Year3_sem1/AILP/ailp_env/share/locale'
LOCALSTATEDIR = '/media/Data/Year3_sem1/AILP/ailp_env/var'
MANDIR = '/media/Data/Year3_sem1/AILP/ailp_env/share/man'
OLDINCLUDEDIR = '/usr/include'
PACKAGE = 'pycairo'
PDFDIR = '/media/Data/Year3_sem1/AILP/ailp_env/share/doc/pycairo'
PKGCONFIG = '/usr/bin/pkg-config'
PREFIX = '/media/Data/Year3_sem1/AILP/ailp_env'
PSDIR = '/media/Data/Year3_sem1/AILP/ailp_env/share/doc/pycairo'
PYC = 1
PYCMD = '"import sys, py_compile;py_compile.compile(sys.argv[1], sys.argv[2])"'
PYFLAGS = ''
PYFLAGS_OPT = '-O'
PYO = 1
PYTHON = ['/media/Data/Year3_sem1/AILP/ailp_env/bin/python']
PYTHONARCHDIR = ['/media/Data/Year3_sem1/AILP/ailp_env/lib/python3.4/site-packages']
PYTHONDIR = '/media/Data/Year3_sem1/AILP/ailp_env/lib/python3.4/site-packages'
PYTHON_CONFIG = '/usr/bin/python3.4-config'
PYTHON_VERSION = '3.4'
RPATH_ST = '-Wl,-rpath,%s'
SBINDIR = '/media/Data/Year3_sem1/AILP/ailp_env/sbin'
SHAREDSTATEDIR = '/media/Data/Year3_sem1/AILP/ailp_env/com'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STLIBPATH_ST = '-L%s'
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
SYSCONFDIR = '/media/Data/Year3_sem1/AILP/ailp_env/etc'
cfg_files = ['/media/Data/Year3_sem1/AILP/ailp_env/pycairo-1.10.0/build_directory/src/config.h']
cprogram_PATTERN = '%s'
cshlib_PATTERN = 'lib%s.so'
cstlib_PATTERN = 'lib%s.a'
define_key = []
macbundle_PATTERN = '%s.bundle'
pyext_PATTERN = '%s.cpython-34m.so'
